Simplify script to fetch latest CLI version from Axon
verily-src/workbench-app-devcontainers pull request #27
Opened 2023-11-14 01:48 UTC by dexamundsen

Changes similar to https://github.com/verily-src/terra-tool-cli/pull/342

2023-11-14 15:45 UTC, yuhuyoyo commented
could you kindly add this change here https://github.com/verily-src/workbench-app-devcontainers/blob/master/startupscript/post-startup.sh#L110 too :) i forgot to add the version check

2023-11-14 15:47 UTC, yuhuyoyo approved these changes

2023-11-14 15:52 UTC, rogerwangcs approved these changes

2023-11-14 17:05 UTC, mbookman requested changes
Some small nits

2023-11-14 17:05 UTC, mbookman commented on startupscript/vertex-ai-user-managed-notebook/post-startup.sh
> +      >&2 echo "ERROR: $TERRA_SERVER is not a known server"
```
     >&2 echo "ERROR: ${TERRA_SERVER} is not a known server"
```

2023-11-15 00:20 UTC, dexamundsen commented on startupscript/dataproc/startup.sh
> +      >&2 echo "ERROR: $TERRA_SERVER is not a known server"
done

2023-11-15 00:21 UTC, dexamundsen commented on startupscript/dataproc/startup.sh
> +  cliDistributionPath="$(echo "$versionJson" | jq -r '.cliDistributionPath')"
done

2023-11-15 00:23 UTC, dexamundsen commented on startupscript/vertex-ai-user-managed-notebook/post-startup.sh
> +      >&2 echo "ERROR: $TERRA_SERVER is not a known server"
done

2023-11-15 19:12 UTC, dexamundsen commented on startupscript/dataproc/startup.sh
>      curl -L https://storage.googleapis.com/${cliDistributionPath#gs://}/download-install.sh | TERRA_CLI_SERVER=${TERRA_SERVER} bash && \
This is part of the multiline string already within quotes

2023-11-15 19:18 UTC, dexamundsen commented on startupscript/vertex-ai-user-managed-notebook/post-startup.sh
> -readonly PROXY_ENV="/opt/deeplearning/proxy.env"
not used

2023-11-15 19:18 UTC, dexamundsen commented
Added some cleanup, hence re-requested review

2023-11-15 21:07 UTC, mbookman requested changes
Just a few small things...

2023-11-15 21:07 UTC, mbookman commented on startupscript/post-startup.sh
> +if [[ $TERRA_SERVER == *"verily"* ]]; then
```
if [[ "${TERRA_SERVER}" == *"verily"* ]]; then
```

2023-11-15 21:07 UTC, mbookman commented on startupscript/post-startup.sh
> +  if [[ $exit_code -ne 0 ]]; then
```
 if [[ "${exit_code}" -ne 0 ]]; then
```

2023-11-15 21:07 UTC, mbookman commented on startupscript/post-startup.sh
> +  export GCSFUSE_REPO=gcsfuse-$(lsb_release -c -s) \
```
  export GCSFUSE_REPO="gcsfuse-$(lsb_release -c -s)" \
```

2023-11-15 21:07 UTC, mbookman commented on startupscript/vertex-ai-user-managed-notebook/post-startup.sh
> +fi
As above, mark the variable readonly.

2023-11-15 21:07 UTC, mbookman commented on startupscript/vertex-ai-user-managed-notebook/post-startup.sh
> +  if [[ $exit_code -ne 0 ]]; then
```
  if [[ "${exit_code}" -ne 0 ]]; then
```

2023-11-15 21:22 UTC, dexamundsen commented on startupscript/dataproc/startup.sh
done, in all files

2023-11-15 21:23 UTC, dexamundsen commented on startupscript/post-startup.sh
> +  export GCSFUSE_REPO=gcsfuse-$(lsb_release -c -s) \
done, in all files

2023-11-15 21:23 UTC, dexamundsen commented on startupscript/vertex-ai-user-managed-notebook/post-startup.sh
> +  if [[ $exit_code -ne 0 ]]; then
missed it, done in all files

2023-11-15 21:26 UTC, mbookman approved these changes
LGTM!

2023-11-15 21:36 UTC, merged