Add AWS configuration hook called by post-startup.sh.
verily-src/workbench-app-devcontainers pull request #66
Opened 2024-03-07 22:02 UTC by jmczerk

This ports over the configuration that we do in the SageMaker startup scripts to help automate access to Workbench resources from AWS compute.  This will get pared down quite a bit once we implement credential-less AuthN for AWS instances, but that's at least a couple sprints away.

2024-03-08 01:21 UTC, mbookman reviewed
LG. Just a few things...

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +readonly WORKBENCH_WORKSPACE=$(get_metadata_value terra-workspace-id)
```suggestion
readonly WORKBENCH_WORKSPACE="$(get_metadata_value terra-workspace-id)"
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +cat >> "${USER_PROFILE}" << EOM
Can we `s/EOM/EOF` as we've previously used `EOF`?

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +configure_workspace() {
Have encouraged the pattern for functions:

```
function my_fn() {
...
}
readonly -f my_fn
```

Slightly more verbose, but makes the code a bit more readable and marking functions readonly prevents an unpleasant category of bugs from cropping up.

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +  ${WORKBENCH_INSTALL_PATH} workspace set --uuid ${WORKBENCH_WORKSPACE}
```suggestion
  "${WORKBENCH_INSTALL_PATH}" workspace set --uuid "${WORKBENCH_WORKSPACE}"
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +  ${WORKBENCH_INSTALL_PATH} workspace configure-aws --cache-with-aws-vault=true
```suggestion
  "${WORKBENCH_INSTALL_PATH}" workspace configure-aws --cache-with-aws-vault=true
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +  ${WORKBENCH_INSTALL_PATH} resource mount
```suggestion
  "${WORKBENCH_INSTALL_PATH}" resource mount
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +  local USER_SSH_KEY=$(${WORKBENCH_INSTALL_PATH} security ssh-key get --include-private-key --format=JSON)
```suggestion
  local USER_SSH_KEY="$("${WORKBENCH_INSTALL_PATH}" security ssh-key get --include-private-key --format=JSON)"
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +  echo $USER_SSH_KEY | jq -r '.privateSshKey' > ${USER_SSH_DIR}/id_rsa
```suggestion
  echo "${USER_SSH_KEY}" | jq -r '.privateSshKey' > "${USER_SSH_DIR}"/id_rsa
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +  echo $USER_SSH_KEY | jq -r '.publicSshKey' > ${USER_SSH_DIR}/id_rsa.pub
```suggestion
  echo "${USER_SSH_KEY}" | jq -r '.publicSshKey' > "${USER_SSH_DIR}"/id_rsa.pub
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +  chmod 0600 ${USER_SSH_DIR}/id_rsa*
```suggestion
  chmod 0600 "${USER_SSH_DIR}"/id_rsa*
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +  ${WORKBENCH_INSTALL_PATH} resource list --type=GIT_REPO --format json | jq -c .[] | while read ITEM; do
Reformat a little to make it more legible:

```
  "${WORKBENCH_INSTALL_PATH}" resource list --type=GIT_REPO --format json | \
    jq -c .[] | \
    while read ITEM; do
      local GIT_REPO_NAME="$(echo $ITEM | jq -r .id)"
      local GIT_REPO_URL="$(echo $ITEM | jq -r .gitRepoUrl)"
      if [[ ! -d "${GIT_REPO_NAME}" ]]; then
        git clone "${GIT_REPO_URL}" "${GIT_REPO_NAME}"
      fi
    done
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +if [ $(${WORKBENCH_INSTALL_PATH} auth status --format json | jq .loggedIn) == false ]; then
```suggestion
if [[ "$("${WORKBENCH_INSTALL_PATH}" auth status --format json | jq .loggedIn)" == false ]]; then
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +    ${WORKBENCH_INSTALL_PATH} auth login
```suggestion
    "${WORKBENCH_INSTALL_PATH}" auth login
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/post-startup.sh
> +readonly USER_PRIMARY_GROUP="$(id --group --name ${USER_NAME})"
```suggestion
readonly USER_PRIMARY_GROUP="$(id --group --name "${USER_NAME}")"
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/post-startup.sh
> +source ${CLOUD_SCRIPT_DIR}/vm-metadata.sh
```suggestion
source "${CLOUD_SCRIPT_DIR}"/vm-metadata.sh
```

2024-03-08 01:21 UTC, mbookman commented on startupscript/post-startup.sh
> +source ${CLOUD_SCRIPT_DIR}/resource-mount.sh
```suggestion
source "${CLOUD_SCRIPT_DIR}"/resource-mount.sh
```

2024-03-08 18:38 UTC, jmczerk commented
Thank you for the thorough review @mbookman !  I especially appreciate you adding the suggested changes.

I've been trying to use `shellcheck` in VSCode locally to try to be cleaner, but this doesn't help with heredoc embedded code...  I'm considering maybe breaking these kind of things into separate files so they can be linted, but that also might clutter the directory a bit (and I'm guessing the import syntax might be ugly?)

I am also considering adding a `shellcheck` PR check workflow using something like [this](https://github.com/ludeeus/action-shellcheck).

WDYT?

2024-03-11 18:34 UTC, mbookman commented
> I've been trying to use shellcheck in VSCode locally to try to be cleaner, but this doesn't help with heredoc embedded code... I'm considering maybe breaking these kind of things into separate files so they can be linted, but that also might clutter the directory a bit (and I'm guessing the import syntax might be ugly?)

If we can establish clear patterns (a little work on file/directory layout and some documentation) for maintainers to follow, I am a fan of using off-the-shelf and custom tooling for better code hygiene. Getting 70% of the way there is usually just annoying enough to make it harder to maintain and getting 90% of the way there gets you the benefits without the cost of dotting all the i's and crossing all the t's.

2024-03-13 19:23 UTC, jmczerk commented
@mbookman I ended up breaking out the literal heredocs that get appended to `.bashrc` and `.bash_profile` out into separate files so that they will be linted with `shellcheck` when https://github.com/verily-src/workbench-app-devcontainers/pull/67 goes in.  PTAL and approve if you're satisfied (I'd like to get this in ahead of the shellcheck PR).

2024-03-14 21:08 UTC, mbookman requested changes

2024-03-14 21:08 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +    https://github.com/99designs/aws-vault/releases/download/v7.2.0/aws-vault-linux-amd64
It's a nit, but I think this URL would be good as a variable defined up with the install path.

2024-03-14 21:08 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +readonly WORKBENCH_WORKSPACE AWS_CONFIG_FILE
I'd like for us to have the pattern of one variable per line. I don't love using more vertical space, but I think it reads easier.

```suggestion
readonly WORKBENCH_WORKSPACE
readonly AWS_CONFIG_FILE

```

2024-03-14 21:08 UTC, mbookman commented on startupscript/aws/post-startup-hook.sh
> +cat "${CLOUD_SCRIPT_DIR}/bash-profile-append.bash" >> "${USER_BASH_PROFILE}"
Missing EOL.

2024-03-14 21:08 UTC, mbookman commented on startupscript/post-startup.sh
> +    source "${CLOUD_SCRIPT_DIR}/post-startup-hook.sh"
```suggestion
  source "${CLOUD_SCRIPT_DIR}/post-startup-hook.sh"
```

2024-03-20 13:33 UTC, jmczerk commented
I think all of the concerns have been addressed, PTAL @mbookman , @yuhuyoyo.

2024-03-20 13:46 UTC, yuhuyoyo approved these changes

2024-03-20 13:46 UTC, yuhuyoyo commented on startupscript/post-startup.sh
> +chown "${USER_NAME}:${USER_PRIMARY_GROUP}" "${USER_BASH_PROFILE}"
do you mind fixing it here too? https://github.com/verily-src/workbench-app-devcontainers/blob/master/startupscript/install-java.sh#L16

2024-03-21 16:45 UTC, mbookman approved these changes
LGTM

2024-03-21 16:50 UTC, merged