Add shellcheck step to PR workflow.
verily-src/workbench-app-devcontainers pull request #67
Opened 2024-03-08 19:07 UTC by jmczerk

2024-03-08 19:48 UTC, jmczerk commented
Ignoring [SC1090](https://www.shellcheck.net/wiki/SC1090), [SC1091])(https://www.shellcheck.net/wiki/SC1091) out of the gate, as `shellcheck` seems to have limitations around dynamic file resolution that lead to lots of false positives.

Distribution of existing errors:

40 x [SC2155 - Declare and assign separately to avoid masking return values.](https://www.shellcheck.net/wiki/SC2155)
12 x [SC2086 - Double quote to prevent globbing and word splitting.](https://www.shellcheck.net/wiki/SC2086)
5 x [SC2034 - foo appears unused. Verify it or export it.](https://www.shellcheck.net/wiki/SC2034)
1 x [SC2016 - Expressions don't expand in single quotes, use double quotes for that.](https://www.shellcheck.net/wiki/SC2016)
1 x [SC2046 - Quote this to prevent word splitting.](https://www.shellcheck.net/wiki/SC2046)
1 x [SC2145 - Argument mixes string and array. Use * or separate argument.](https://www.shellcheck.net/wiki/SC2145)
1 x [SC2164 - Use `cd ... || exit` in case cd fails.](https://www.shellcheck.net/wiki/SC2164)
1 x [SC2207 - Prefer `mapfile` or `read -a` to split command output (or quote to avoid splitting).](https://www.shellcheck.net/wiki/SC2207)

2024-03-11 17:56 UTC, mbookman commented
Thanks @jmczerk ! 

I am a big fan of this, at least conceptually. I haven't used `shellcheck`, so I don't know if we'd find ourselves battling various cases. That's usually a low-cost battle for the upside, though.

I've hesitated to enforce [SC2155](https://www.shellcheck.net/wiki/SC2155) as we declare/execute usually on well-exercised code paths, but enforcing it would avoid a category of painful bugs creeping in.

+1!

2024-03-14 22:00 UTC, mbookman requested changes

2024-03-14 22:48 UTC, jmczerk commented on startupscript/git-setup.sh
> +readonly WORKBENCH_GIT_REPOS_DIR="${WORK_DIRECTORY}/repos"
I think there may be value in this; could we maybe capture a Jira ticket to do this in a follow-on?  

I've tried to minimize structural/logic changes in this PR given the large number of changes, and the test cycles across Vertex AI + Dataproc + Mikey custom apps has stretched this beyond the time I budgeted for it.  Are you OK with deferring?

2024-03-18 18:41 UTC, jmczerk commented on startupscript/git-setup.sh
> +readonly WORKBENCH_GIT_REPOS_DIR="${WORK_DIRECTORY}/repos"
@mbookman buming this question

2024-03-18 22:04 UTC, mbookman approved these changes
LGTM

2024-03-19 14:36 UTC, rogerwangcs approved these changes
lgtm! Are there any local dev environment setup to properly enable shellcheck? Is it a command we run? Is it integrated with vscode/intellij? If so, it may be worth adding to a `CONTRIBUTINGmd`

2024-03-19 14:36 UTC, rogerwangcs commented on .github/workflows/test-pr.yaml
> +          SHELLCHECK_OPTS: -e SC1090 -e SC1091
Could we add a comment that describes these two lint rules?

2024-03-19 14:38 UTC, jmczerk commented
> lgtm! Are there any local dev environment setup to properly enable shellcheck? Is it a command we run? Is it integrated with vscode/intellij? If so, it may be worth adding to a `CONTRIBUTING.md`

There's a new section in `startupscripts/README.md` for this, as that seemed to be where all the startup script docs lived.

2024-03-19 14:44 UTC, rogerwangcs commented
> There's a new section in `startupscripts/README.md` for this, as that seemed to be where all the startup script docs lived.

Missed this, thanks.

2024-03-19 14:58 UTC, merged